### ISSUE TITLE
Difficulty using with multiple instances of same block

### ISSUE THREAD

**Issue by Jmuccigr** [omeka-s-modules/CSSEditor#6]
I'd like to be able to apply different css rules when there are different kinds of items being shown in the same kind of blocks. For example, a Showcase of text items (like bibliography) versus a Showcase of images. The pages' codings are so similar that I don't see an obvious way of applying different CSS.

So the question is whether it's possible to apply the css by the page, instead of by the site. Or would it take some change in the coding so that one can find some hook to hang the css on.

(Alternatively I could be wrong and there is a way to do it already.)

**Comment by kimisgold** [comment]
I'm wondering if a different block type would be more suitable for your text items. Have you tried using the Browse Preview block? That would display your text bibliography as a list of links. Item showcase prioritizes items with visual media attachments by design.

There is no obvious way of applying different CSS for text vs visual media attachments in the item showcase block. If you really need to use the item showcase specifically, my recommendation is to create a custom override of the item showcase block within your theme. This means copying `application/view/common/block-layout/item-showcase.phtml` into `themes/your-theme/view/common/block-layout`, creating the necessary subdirectories. In your custom override, you could create different classes for the rendered item based on whether it has a media attachment.

**Comment by Jmuccigr** [comment]
I tried that, but was not successful in finding search terms that gave me only the bibliography items. Any help with that appreciated.

**Comment by kimisgold** [comment]
I'd have to get a better understanding of how you create your bibliography items. Are you using a resource template or class? Is there a metadata field you're using to identify your bibliographies?

**Comment by Jmuccigr** [comment]
I finally got the Browse Preview to work, but it took a bit of doing. Not sure why, but I wasn't getting a good search string, it seems.

To answer your questions, I import the bibliography items with the Zotero import module, which gives them an appropriate bibliographic type for their class (e.g., Book, Book section). Then I add them to an Item Set and search for that set in the Browse Preview. As far as I know, I'm not using any special templates.

**Comment by kimisgold** [comment]
Querying for the item set would've been my recommendation, and I'm glad you were able to come to the same conclusion.
